apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "delete", "list", "update"]